/*jshint esversion: 6 */

// array of all color btns
let btnColors = ['green', 'red', 'yellow', 'blue'];

// array for game generated pattern and userClickedPattern
let gamePattern = [];
let userClickedPattern = [];
let repeatGamePattern = [];

// setting a switch, when a key is pressed then start the game
let started = false;

// User select color variable
let userSelectedColor;

let x = 0;

// defining the levels of each pattern generated by the game
let level = 0;

// onclick event for simon-instructions.html page
$(document).on('click', function () {
  $('.welcome-title').fadeOut(1000);
  $('.display-on-load').show();
});

// onscroll event for simon-instructions.html page
$(document).scroll(function () {
  $('.welcome-title').fadeOut(1000);
  $('.display-on-load').show();
});

// onkeypress event for simon-instructions.html page as well as for simon-game.html page
$(document).keypress(function () {
  $('.welcome-title').fadeOut(1000);
  $('.display-on-load').show();

  // start the game pattern when the landing page is simon-game.html and detect the first keypress
  if (!started && location.pathname.split('/').includes('simon-game.html')) {

    // simonGame() to start the game pattern sequence
    simonGame();

    // key is now pressed setting started=true so that no other key
    // should be pressed untill the game is over
    started = true;
  }
});

// simonGame() to start the game pattern sequence
function simonGame() {

  console.log('-------------------------');

  // after gameovers making userClickedPattern empty to start the next pattern after game is over
  userClickedPattern = [];

  // Increasing the level as the game progress
  level++;

  // changing the heading on simon-game.html
  $('.game-page-heading').text('Level ' + level);

  // taking a random value from 0-3 as array is started from 0th index
  var randomGameTile = Math.floor(Math.random() * 4);

  // select the color from btnColors array on the basis of randomGameTile generated
  var randomGameTileColorSelected = btnColors[randomGameTile];

  // pushing the selected color from btnColors to gamePattern which is the game generated pattern
  gamePattern.push(randomGameTileColorSelected);

  for (let i = 0; i < gamePattern.length; i++) {

    // adding the class to the game tile to change the color and play the audio
    console.log('gamePattern: ' + gamePattern[i]);
    $('.game-tile-' + gamePattern[i]).addClass('event-game-tile-' +
    gamePattern[i]);
    new Audio('sounds/' + gamePattern[i] + '.wav').play();

    // removing the class from the game tile to change the color and play the audio
    setTimeout(
      function () {
        $('.game-tile-' + gamePattern[i]).removeClass('event-game-tile-' +
        gamePattern[i]);
      }, 400);
  }

  console.log('-------------------------');
}

// On USer Btn click run the anonymous fumction
$('.game-tile').click(function () {

  // selecting the game-tile ID to get the current Color
  userSelectedColor = $(this).attr('id');

  console.log('userSelectedColor: ' + userSelectedColor);

  console.log('-------------------------');

  // pushing the selected id from userclick into userClickedPattern array
  userClickedPattern.push(userSelectedColor);

  console.log('userClickedPattern: ' + userClickedPattern);

  // playing the sound as per btn clicked by user
  if (userSelectedColor != gamePattern[gamePattern.length - 1] &&
    !gamePattern.includes(userSelectedColor))
    new Audio('sounds/wrong.mp3').play();
  else
    new Audio('sounds/' + userSelectedColor + '.wav').play();

  // animate the btn clicked by user
  animateBtn(userSelectedColor);

  // Now check the userClickedPattern and game generated pattern
  checkAnswer(userClickedPattern.length - 1);
});

// verify the result from userClickedPattern and gamePattern
function checkAnswer(currentLevel) {

  // if the userClickedPattern data present in gamePattern generated by game
  if (gamePattern[currentLevel] === userClickedPattern[currentLevel]) {

    // if the lenght in both the arrays are equal then proceed with the next pattern
    if (userClickedPattern.length === gamePattern.length) {

      // run the next pattern after 1 second
      setTimeout(function () {
        simonGame();
      }, 1000);
    }
  } // if the userClickedPattern data not present in gamePattern generated by game
  else {
    // game-over audio with red color flash and the message
    new Audio('sounds/wrong.mp3').play();
    $('body').addClass('game-over');
    $('.game-page-heading').text('Game Over, Press Any Key to Restart');

    // remove the game-over class after 200 milliseconds
    setTimeout(function () {
      $('body').removeClass('game-over');
    }, 200);

    // restart the game
    startOver();
  }
}

// Animation btn function
function animateBtn(userSelectedColor) {
  $('#' + userSelectedColor).addClass('pressed');
  setTimeout(function () {
    $('#' + userSelectedColor).removeClass('pressed');
  });
}

// game restart
function startOver() {
  level = 0;
  gamePattern = [];
  started = false;
}
